name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Jeśli Twoja aplikacja wymaga kompilacji/budowania, np. transpile ES6, uruchom poniższy krok:
      - name: Build application
        run: npm run build

      - name: Deploy to Production
        run: echo "Deploying to production..."
        # Tutaj możesz dodać kroki wdrożeniowe, np. wysyłkę plików przez scp, użycie Heroku CLI, itp.
